name: FirstWorkflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      -name: Print greeting
        run: echo "Hello World, my name is Shaylin Naidoo." 
      -name: Print goodbye 
        run: echo "Goodbye World, I will miss you."
      
